### ISSUE TITLE
Sec-WebSocket-Protocol实现错误

### ISSUE THREAD

**Issue by lxzan** [antlabs/quickws#12]
不能把Sec-WebSocket-Protocol原封不动的返回给客户端. 
客户端请求头里面可能包含多个子协议:

```js
let ws = new WebSocket('ws://127.0.0.1:9001/connect', ['chat', 'game']);
```

服务端如果支持子协议, 应该选择一个服务端子协议支持列表和客户端请求的交集, 返回给客户端; 不支持的话, 忽略此Header.

**Comment by lxzan** [comment]
用Sec-WebSocket-Protocol来做鉴权, 实属歪门邪道 😂

**Comment by guonaihong** [comment]
> 用Sec-WebSocket-Protocol来做鉴权, 实属歪门邪道 😂

一开始我的想法和你类似，用Sec-WebSocket-Protocol传递token有奇怪。直到看到 https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api 这个贴子，很容易引导用户使用new WebSocket第二个参数传递token。

后面我想了下，对于Sec-WebSocket-Protocol的处理，可以很2个case。如果服务设置了子协议，只返回和客户端的交集，如服务没有设置子协议就echo下。

**Comment by lxzan** [comment]
本质还是JS API有缺陷, 不允许使用自定义header

**Comment by guonaihong** [comment]
> 本质还是JS API有缺陷, 不允许使用自定义header

是的。

**Comment by guonaihong** [comment]
> 
> 后面想了下，对于Sec-WebSocket-Protocol的处理，可以分成2个case。如果服务设置了子协议，只返回和客户端的交集，如服务没有设置子协议就echo下。
> 
> 周六晚上只完成这个想法的50%，提升兼容性。

剩余的50%已加到main分支。
