### ISSUE TITLE
有没有和gin结合的例子

### ISSUE THREAD

**Issue by zzdboy** [antlabs/quickws#9]
gin如何结合例子

而且你的测试代码会报以下错误 

read tcp 192.168.20.86:9001->192.168.20.86:57339: i/o timeout

**Comment by guonaihong** [comment]
## 服务端
```go
package main

import (
	"fmt"

	"github.com/antlabs/quickws"
	"github.com/gin-gonic/gin"
)

type handler struct{}

func (h *handler) OnOpen(c *quickws.Conn) {
	fmt.Printf("服务端收到一个新的连接")
}

func (h *handler) OnMessage(c *quickws.Conn, op quickws.Opcode, msg []byte) {
	// 如果msg的生命周期不是在OnMessage中结束，需要拷贝一份
	// newMsg := makc([]byte, len(msg))
	// copy(newMsg, msg)

	fmt.Printf("收到客户端消息:%s\n", msg)
	c.WriteMessage(op, msg)
	// os.Stdout.Write(msg)
}

func (h *handler) OnClose(c *quickws.Conn, err error) {
	fmt.Printf("服务端连接关闭:%v\n", err)
}

func main() {
	r := gin.Default()
	r.GET("/ws", func(c *gin.Context) {
		con, err := quickws.Upgrade(c.Writer, c.Request, quickws.WithServerCallback(&handler{}))
		if err != nil {
			return
		}
		con.StartReadLoop()
	})
	r.Run()
}

```

## 客户端
```go
package main

import (
	"fmt"
	"time"

	"github.com/antlabs/quickws"
	"github.com/antlabs/wsutil/opcode"
)

type handler struct{}

func (h *handler) OnOpen(c *quickws.Conn) {
	fmt.Printf("客户端连接成功\n")
}

func (h *handler) OnMessage(c *quickws.Conn, op quickws.Opcode, msg []byte) {
	// 如果msg的生命周期不是在OnMessage中结束，需要拷贝一份
	// newMsg := makc([]byte, len(msg))
	// copy(newMsg, msg)

	fmt.Printf("收到服务端消息:%s\n", msg)
	c.WriteMessage(op, msg)
	time.Sleep(time.Second)
}

func (h *handler) OnClose(c *quickws.Conn, err error) {
	fmt.Printf("客户端端连接关闭:%v\n", err)
}

func main() {
	c, err := quickws.Dial("ws://127.0.0.1:8080/ws", quickws.WithClientCallback(&handler{}))
	if err != nil {
		fmt.Printf("连接失败:%v\n", err)
		return
	}

	c.WriteMessage(opcode.Text, []byte("hello"))
	c.ReadLoop()
}

```

**Comment by zzdboy** [comment]
以下代码是我项目里实现的，使用Apifox测试并没有正常连接到websocket

无法连接到 ws://192.168.20.86:9000/quickws/notify


Sec-WebSocket-Version | 13
Sec-WebSocket-Key | zFCCOblI6P1p/hUL1tIOWQ==
Connection | Upgrade
Upgrade | websocket
Authorization | eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNjkzNjEzNDkxLCJuYmYiOjE2OTM1MjcwOTEsImlhdCI6MTY5MzUyNzA5MX0.MNNsjTGfZrwMkKeRONHwLTfQCJTDQs4Yl5pJObgRV0k
User-Agent | Apifox/1.0.0 (https://apifox.com)
Sec-WebSocket-Extensions | permessage-deflate; client_max_window_bits
Host | 192.168.20.86:9000

`package controllers

import (
	"fmt"

	"github.com/antlabs/quickws"
	"github.com/gin-gonic/gin"
)

type Quickws struct {
}

// Index测试服务
func (e *Quickws) Index(ctx *gin.Context) {
	c, err := quickws.Upgrade(ctx.Writer, ctx.Request, quickws.WithServerCallback(&Quickws{}))
	if err != nil {
		fmt.Println("Upgrade fail:", err)
		return
	}

	c.StartReadLoop()
}

func (e *Quickws) OnOpen(c *quickws.Conn) {
	fmt.Printf("服务端收到一个新的连接")
}

func (e *Quickws) OnMessage(c *quickws.Conn, op quickws.Opcode, msg []byte) {
	// 如果msg的生命周期不是在OnMessage中结束，需要拷贝一份
	// newMsg := makc([]byte, len(msg))
	// copy(newMsg, msg)

	fmt.Printf("收到客户端消息:%s\n", msg)
	c.WriteMessage(op, msg)
	// os.Stdout.Write(msg)
}

func (e *Quickws) OnClose(c *quickws.Conn, err error) {
	fmt.Printf("服务端连接关闭:%v\n", err)
}
`

路由层
`func (d *QuickwsRouter) LoadQuickwsRoutes(r *gin.Engine) {

	// 添加跨域中间件

	QuickwsController := &controllers.Quickws{}

	websocketGroup := r.Group("/quickws")
	{
		// 首页路由
		websocketGroup.GET("/notify", QuickwsController.Index)
	}

	// 其他路由...
}`

**Comment by guonaihong** [comment]
postman倒是跑过，我下载个apifox看看。

**Comment by guonaihong** [comment]
我这边可以的。你翻墙了？
<img width="1114" alt="image" src="https://github.com/antlabs/quickws/assets/5006959/081867bd-9f4f-41ed-9b7c-a87c9d336a36">

**Comment by zzdboy** [comment]
退了翻墙测试的。。而且只是Google Chrome浏览器翻墙
![1693541362596](https://github.com/antlabs/quickws/assets/3378222/417f4bc6-1713-4122-b6a9-164da8654601)
![1693541390367](https://github.com/antlabs/quickws/assets/3378222/09daed89-d759-42c0-bf3c-84f0f2047d02)
![1693541413982](https://github.com/antlabs/quickws/assets/3378222/f5b09a2b-19b1-4a98-ae97-df1551d93fe0)

**Comment by guonaihong** [comment]
wireshark抓包我看下。

**Comment by guonaihong** [comment]
gin起来的控制台信息发下呢。
<img width="934" alt="image" src="https://github.com/antlabs/quickws/assets/5006959/ac672f29-48ce-4027-a527-5a53b680a0b6">
<img width="834" alt="image" src="https://github.com/antlabs/quickws/assets/5006959/bb648964-0f39-4667-b42a-ed4c81153a10">
和你一样的代码，apifox是可以的，大概率还是和你的网络设置有关系的。

<img width="957" alt="image" src="https://github.com/antlabs/quickws/assets/5006959/09958a39-a4c7-4c95-988a-53ccd8a02b86">

**Comment by guonaihong** [comment]
或者你把Index里面的代码都注释掉，打印一句话，apifox使用GET方法发个请求再看下结果如何。

**Comment by zzdboy** [comment]
进过测试可以了，谢谢

**Comment by guonaihong** [comment]
跑成功就行，那这个issue我先关闭了。

**Comment by zzdboy** [comment]
用apifox是连接上了，，但前端还是一直报这个错误 WebSocket connection to 'ws://192.168.20.86:9000/quickws/notify' failed:

**Comment by guonaihong** [comment]
> 用apifox是连接上了，，但前端还是一直报这个错误 WebSocket connection to 'ws://192.168.20.86:9000/quickws/notify' failed:

前端要用wss，服务端打开ssl证书，可以服务端前面套个nginx连下。

**Comment by guonaihong** [comment]
我这边前端代码也跑过，可以的。

https://github.com/antlabs/quickws-example/blob/master/with-html/server/server.go

这是前端连的代码
https://github.com/antlabs/quickws-example/blob/master/templates/index.html

**Comment by zzdboy** [comment]
很是奇怪，，我单独的页面就成功，但一放在vue项目里。WebSocket就失败。。一直找不到原因
![1693548907344](https://github.com/antlabs/quickws/assets/3378222/7a3cdd52-4ea1-47ff-90f8-d855ba976382)
![1693548935287](https://github.com/antlabs/quickws/assets/3378222/570639df-d910-40a7-b051-63a26b3a0604)

**Comment by guonaihong** [comment]
你看下是不是跨域问题。

**Comment by guonaihong** [comment]
问题可解决？祼的html可连，带vue不能连。

**Comment by zzdboy** [comment]
应该不是跨域问题..其它页面都是可以跨域，，唯独websocket有问题..没找到原因

**Comment by zzdboy** [comment]
前端换了个SockJS 连接websocket，，显示跨域问题
![1693621611213](https://github.com/antlabs/quickws/assets/3378222/71d39c4a-dd8f-413d-91eb-f186f42832db)

**Comment by guonaihong** [comment]
你看下Access-Control-Allow-Origin 这个header的返回值。

**Comment by zzdboy** [comment]
返回值是 http://192.168.101.48:8080..也正常。。其它http请求都没有问题。。就ws请求有问题
![1693627201697](https://github.com/antlabs/quickws/assets/3378222/db9328d6-d117-43f8-bd9c-cbe967b0a218)

**Comment by guonaihong** [comment]
响应头怎么是0的？websocket依赖的gin服务加cors中件间了吗？

**Comment by zzdboy** [comment]
![1693627460884](https://github.com/antlabs/quickws/assets/3378222/8fa11f68-b9dd-4c4b-8891-fbb33f7e2ec9)

**Comment by guonaihong** [comment]
把 Access-Control-Allow-Origin 的值设置为*
把
<img width="535" alt="image" src="https://github.com/antlabs/quickws/assets/5006959/dd3b7bfc-2c38-4afd-929e-648cdcc31109">
这一行去掉。

**Comment by zzdboy** [comment]
去掉了所有接口都不能访问了
![1693632961760](https://github.com/antlabs/quickws/assets/3378222/55964776-0f4f-4db1-bedc-0ae14b9233ee)
![1693632979058](https://github.com/antlabs/quickws/assets/3378222/4870ee33-178c-4ff3-b8c0-7fc187edb410)

**Comment by guonaihong** [comment]
https://stackoverflow.com/questions/20035101/why-does-my-javascript-code-receive-a-no-access-control-allow-origin-header-i

看下这个贴子。
我记得以前解决跨域，就写了 Access-Control-Allow-Origin 的值设置为*

**Comment by guonaihong** [comment]
<img width="555" alt="image" src="https://github.com/antlabs/quickws/assets/5006959/b1200403-3721-4410-8c43-75e4cd034815">

**Comment by zzdboy** [comment]
前台端端口不能用同一个端口吧。。我后端是gin 9000端口，，前端用Vue是8080端口。。如果后端也设置成8008..前端启动他会自动设置为8081端口

**Comment by guonaihong** [comment]
我记得以前只用 把 Access-Control-Allow-Origin 的值设置为*，就可以解决跨域问题了。

**Comment by zzdboy** [comment]
是，，我以前用其它框架都是Access-Control-Allow-Origin 的值设置为*也就可以了。但前几天后端换成gin框架后就出现这样的问题，一直找不到原因
![1693634648156](https://github.com/antlabs/quickws/assets/3378222/96cee7b2-01c6-4bc9-95d9-d6c942c7b15e)

**Comment by zzdboy** [comment]
ctx.Header("Access-Control-Allow-Headers", "Accept, Authorization, Origin, X-Requested-With, Content-Type, Accept")
Access-Control-Allow-Header要设置成和前端一样，但websocket还是不能请求, 响应请求头还是0
![1693635750786](https://github.com/antlabs/quickws/assets/3378222/e74f6cb8-d119-4379-b1e7-fd62eea89454)

**Comment by guonaihong** [comment]
"Access-Control-Allow-Headers" 也设置成 * 试下

**Comment by zzdboy** [comment]
websocket还是不能通讯
![1693636475275](https://github.com/antlabs/quickws/assets/3378222/e0e0ab88-b813-423c-87f6-f27b1069c264)

**Comment by guonaihong** [comment]
浏览器报错的信息截个图呢。

**Comment by zzdboy** [comment]
![1693636670338](https://github.com/antlabs/quickws/assets/3378222/5d02aa78-decf-44d1-b6cc-5ebb84d8c00c)
![1693636690871](https://github.com/antlabs/quickws/assets/3378222/b3754cf0-46d1-4e86-8f9b-63ed920be9e5)

**Comment by guonaihong** [comment]
<img width="556" alt="image" src="https://github.com/antlabs/quickws/assets/5006959/7fa0c781-16f9-4536-95ca-299e6352a90e">
这里点开的结果是？

**Comment by zzdboy** [comment]
![1693636998411](https://github.com/antlabs/quickws/assets/3378222/f1db08e5-a726-41b1-a878-13be8281b01c)
![1693637034923](https://github.com/antlabs/quickws/assets/3378222/802e2543-ac03-4f40-a47a-039a845dff96)

**Comment by guonaihong** [comment]
把websocket加cors的代码贴下。

**Comment by zzdboy** [comment]
![1693637783090](https://github.com/antlabs/quickws/assets/3378222/bb3796d4-0dca-4877-939d-1203d58c1b5e)
![1693637994204](https://github.com/antlabs/quickws/assets/3378222/b2535fff-012a-4c9a-a456-82f391cad94f)

**Comment by zzdboy** [comment]
按这个也不启作用
https://blog.csdn.net/z914020826/article/details/127232233

**Comment by guonaihong** [comment]
直接抓个包，我看下。

**Comment by zzdboy** [comment]
有远程不，，可以帮我直接看下。。
![1693638592455](https://github.com/antlabs/quickws/assets/3378222/6559dde5-d0a8-4dca-9813-94f87bac38ae)

**Comment by guonaihong** [comment]
今天加班，还有几个bug要修复下。只能抽时间帮你看下。

右击，过滤流。

**Comment by 91he** [comment]
> 应该不是跨域问题..其它页面都是可以跨域，，唯独websocket有问题..没找到原因 基本都是一连接websocket后就关闭了 ![1693615669349](https://user-images.githubusercontent.com/3378222/265156317-0e066da7-540d-48ce-b40a-213eb2aa4242.png) ![1693615993251](https://user-images.githubusercontent.com/3378222/265157035-d9a664a7-ec7e-4efa-94c2-07c46ae178bd.png)

@zzdboy 问题出在这里，ws路由不需要跨域配置，websocket不存在跨域问题。

**Comment by zzdboy** [comment]
@91he gin如何指定不让websocket跨域

**Comment by guonaihong** [comment]
> 有远程不，，可以帮我直接看下。。 ![1693641900054](https://user-images.githubusercontent.com/3378222/265190420-010cf89d-e317-45f6-af64-c55835fbf91e.png)
把这个包发我邮箱 guonaihong@qq.com

**Comment by zzdboy** [comment]
我重新修改代码，，所路跨域中间件不做全局设置，在路由组上设置跨域中间件，，但是跨域不启作用
![1693645867320](https://github.com/antlabs/quickws/assets/3378222/c7675508-cd06-427d-9bcd-fc0c9660623d)
![1693645892816](https://github.com/antlabs/quickws/assets/3378222/d61af608-c9ee-4543-bd62-517af4062e3a)

**Comment by zzdboy** [comment]
@guonaihong 加我VX:zzdboy

**Comment by guonaihong** [comment]
> > 有远程不，，可以帮我直接看下。。 ![1693641900054](https://user-images.githubusercontent.com/3378222/265190420-010cf89d-e317-45f6-af64-c55835fbf91e.png)
> 
> 把这个包发我邮箱 [guonaihong@qq.com](mailto:guonaihong@qq.com)

内容不对。只有2个字节。

**Comment by guonaihong** [comment]
> @guonaihong 加我VX:zzdboy
抱歉啊，我有点社恐。

**Comment by zzdboy** [comment]
![1693648241892](https://github.com/antlabs/quickws/assets/3378222/d8d5c4b3-02d6-42d1-b953-3ecc480474ad)
@guonaihong

**Comment by zzdboy** [comment]
你要看哪块的数据 或直接远程你帮我看看
![1693649292109](https://github.com/antlabs/quickws/assets/3378222/08d0221b-f73f-4094-b9ba-129eae07ae02)

**Comment by guonaihong** [comment]
<img width="660" alt="image" src="https://github.com/antlabs/quickws/assets/5006959/fd1a8c1b-38fe-4406-b50a-ef8831869037">
把port换成你的websocket的端口

**Comment by zzdboy** [comment]
@guonaihong  要什么样格式数据
![1693649999986](https://github.com/antlabs/quickws/assets/3378222/901e6ed0-335c-451c-80b4-6b05e92b907c)

**Comment by guonaihong** [comment]
ascii码。 比如这样的包
<img width="739" alt="image" src="https://github.com/antlabs/quickws/assets/5006959/5ec7e45f-d19a-42e3-82af-3bcd78d38cbd">

**Comment by zzdboy** [comment]
我的ascii码是这样的数据
![1693650552524](https://github.com/antlabs/quickws/assets/3378222/7d93e053-aa37-4c79-8eab-ceee881f54e5)

**Comment by guonaihong** [comment]
这数据不像websocket的包。都没有http握手的包。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月2日(周六) 晚上6:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [antlabs/quickws] 有没有和gin结合的例子 (Issue #9)




 
我的ascii码是这样的数据

**Comment by zzdboy** [comment]
@guonaihong 我下载的最新版本，，还真找不到像你版本里看到的哪样数据

**Comment by zzdboy** [comment]
终于让我发现了，，用你昨天发的例子，，同样以下传值，，就会出现这样的错误,你可以试试 @guonaihong 
var token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNjkzNzI2Nzc1LCJuYmYiOjE2OTM2NDAzNzUsImlhdCI6MTY5MzY0MDM3NX0.7U3ipgyo6XBgi5raaATXxLuyMPBCk4MmZPKzUzWXqXY"
        const socket = new WebSocket("ws://127.0.0.1:8888/ws",[token]);

![1693654471713](https://github.com/antlabs/quickws/assets/3378222/68997dc5-63ad-4fc5-9e7e-7da5f52a516d)
![1693654489033](https://github.com/antlabs/quickws/assets/3378222/c5318a17-0ac0-4f9c-a42a-d8b2507c15cb)

**Comment by guonaihong** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/WebSocket/WebSocket
你用的对吗？文档里面WebSocket构造函数第二个参数是子协议。

**Comment by zzdboy** [comment]
这是我上个版本实现的，，webSocket这样用就正常。。奇怪了，，同样是WebSocket 同样用法。
![1693661079014](https://github.com/antlabs/quickws/assets/3378222/dc9c85d9-6865-47c0-a29d-772c4e9860ca)
![1693661108375](https://github.com/antlabs/quickws/assets/3378222/2b6c6adb-0969-4f87-9c37-a2800ab81a3f)
![1693661127166](https://github.com/antlabs/quickws/assets/3378222/47b10b54-f696-4c60-9f8c-ae5814a5782e)

**Comment by guonaihong** [comment]
所以如果第二个参数不传，可以跑通过吗？

**Comment by zzdboy** [comment]
第二个参数不传就正常了,但token我又如何传好呢，，get放在url后面，，又太长。。

**Comment by guonaihong** [comment]
方法1 就是你说的第到url.
方法2 
![Uploading image.png…]()

**Comment by guonaihong** [comment]
方法3: 我修改下quickws 回显子协议的内容，rfc6455对这块的规定是回显或者忽略，quickws一开始选择的方式是忽略。

**Comment by zzdboy** [comment]
js 前端
`    socket= new WebSocket(socket.ws_url,[token]);
`
Gin后端
`// websocket Upgrader
	var wsupgrader = websocket.Upgrader{
		ReadBufferSize:   1024,
		WriteBufferSize:  1024,
		HandshakeTimeout: 5 * time.Second,
		// 取消ws跨域校验
		CheckOrigin: func(r *http.Request) bool {
			return true
		},
		Subprotocols: []string{ctx.Request.Header.Get("Sec-WebSocket-Protocol")},
	}`

**Comment by guonaihong** [comment]
> 现在以下面这种方式实现websocket通讯了 js 前端
> 
> socket= new WebSocket(socket.ws_url,[token]);
> 
> Gin后端
> 
> var wsupgrader = websocket.Upgrader{ ReadBufferSize: 1024, WriteBufferSize: 1024, HandshakeTimeout: 5 * time.Second, // 取消ws跨域校验 CheckOrigin: func(r *http.Request) bool { return true }, Subprotocols: []string{ctx.Request.Header.Get("Sec-WebSocket-Protocol")}, }

恩，你用最新的quickws就支持了。
